name: Update README Activity

on:
  schedule:
    # Runs every hour
    - cron: "0 * * * *"
  workflow_dispatch: # Allows you to run it manually for testing

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Important: allows the action to edit your README
    
    steps:
      - uses: actions/checkout@v4
      - uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          COMMIT_MSG: "⚡ Update README with latest activity"
          MAX_LINES: 10
